/* 
 * This file is part of the GROUCHO project.
 * 
 * GROUCHO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * GROUCHO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GROUCHO.  If not, see <https://www.gnu.org/licenses/>
 *
 */

/*
 * Groucho State Observer
 * Groucho REST API for Monitoring Object State 
 *
 * OpenAPI spec version: 1.0.API.SNAPSHOT
 * Contact: guglielmo.deangelis@iasi.cnr.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */package it.cnr.iasi.saks.groucho.lsh.rest_client;

import it.cnr.iasi.saks.groucho.lsh.StateObserver;
import it.cnr.iasi.saks.groucho.lsh.exceptions.LSHException;
import it.cnr.iasi.saks.groucho.lsh.rest_client.restTemplate.ApiClient;
import it.cnr.iasi.saks.groucho.lsh.rest_client.restTemplate.client.IsStateUnknownApi;
import it.cnr.iasi.saks.groucho.lsh.rest_client.restTemplate.client.MarkStateApi;
import it.cnr.iasi.saks.groucho.lsh.rest_client.restTemplate.client.ResetStateObserverApi;

public class StateObserverRestClient implements StateObserver{

	
	private IsStateUnknownApi isStateUnknownAPI;
	private MarkStateApi markStateApi;
	private ResetStateObserverApi resetStateObserverApi;

	public StateObserverRestClient(String targetURLBasePath) {
        ApiClient apiClient = new ApiClient();
        if ((targetURLBasePath != null) && (!targetURLBasePath.isEmpty())){
        	apiClient= apiClient.setBasePath(targetURLBasePath); 
        }
		
		this.isStateUnknownAPI = new IsStateUnknownApi(apiClient);
		this.markStateApi = new MarkStateApi(apiClient);
	    this.resetStateObserverApi = new ResetStateObserverApi(apiClient);

	}
	
	@Override
	public boolean isStateUnknown(String carvedState) throws LSHException {
		boolean exitus = false; 
		try {
			Object result = this.isStateUnknownAPI.isStateUnknown(carvedState);
			exitus = (boolean) result;
		} catch (Exception e) {
			LSHException lshEx = new LSHException(e);
			throw lshEx;
		}		

		return exitus;
	}

	@Override
	public void markState(String carvedState) throws LSHException {
		boolean exitus = false; 
		try {
			Object result = this.markStateApi.markState(carvedState);
			exitus = (boolean) result;
		} catch (Exception e) {
			LSHException lshEx = new LSHException(e);
			throw lshEx;
		}
		if (!exitus) {
			LSHException lshEx = new LSHException("Unmarked Stated: " + carvedState);
			throw lshEx;			
		}
	}

	@Override
	public void resetStateObserver() throws LSHException {
		boolean exitus = false; 
		try {
			Object result = this.resetStateObserverApi.resetStateObserver();
			exitus = (boolean) result;
		} catch (Exception e) {
			LSHException lshEx = new LSHException(e);
			throw lshEx;
		}
	}

}
