/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.cnr.iasi.saks.groucho.lsh.rest.api;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.annotation.Generated;
@Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-07-02T22:49:41.406+02:00")

@Api(value = "reset", description = "the reset API")
public interface ResetApi {

    @ApiOperation(value = "Suggest to Restore the State of the Observer to the Default Configurations.", nickname = "resetStateObserver", notes = "Suggest to Restore the State of the Observer to the Default Configurations. It is only a suggestion, there is no commitment from the receiver.", tags={ "resetStateObserver", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Operation."),
        @ApiResponse(code = 400, message = "Reset Not Allowed."),
        @ApiResponse(code = 404, message = "Reset Exception.") })
    @RequestMapping(value = "/reset",
        produces = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<Boolean> resetStateObserver();

}
